In [4]:
# 1. Import numpy
import numpy as np


In [5]:
# example code
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [6]:
# A. Array Fundamentals
# salah satu cara inisialisasi array adalah menggunakan python sequence, seperti list:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
# akses array dalam numpy persis seperti di python
# akses elemen array menggunakan index dengann menggunakan square brackets
a[0]

np.int64(1)

In [8]:
# layaknya original list, array mutable (bisa diubah)
a[0]=10
a

array([10,  2,  3,  4,  5,  6])

In [9]:
# bisa slice notation  bisa dengan pengindeksan
a[:3]


array([10,  2,  3])

In [10]:
# perbedaan major, copy list dari original ke list baru, list original akan dimutasi menggunakan view list baru.
b = a[3:]    #list baru (b) copy dari list original (a)
b

array([4, 5, 6])

In [11]:
b[0]=40  #mengganti indeks ke 0 list baru (elemen tiga  terkahir dari list original) dengan 40.
a        # maka list a menampilkan view dari list b

array([10,  2,  3, 40,  5,  6])

In [12]:
# Array dua dimensi dan lebih tinggi dapat diinisialisasi dari nested Python sequences (urutan Python bersarang)
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11, 12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
# axis vs dimensi; kebingungan istilah
# array a terbaru mempunyai tiga titik, di setiap titik berada di ruang 4 dimensi (punya koordinat   x,y,z, dan waktu).
# array a di atas dalam dimensi matematika/fisika itu sudah termasuk 4 dimensi (karena setiap titik punya empat angka penentu). tapi dalam numpy itu hanya sebuah wadah data dalam bentuk tabel. layaknya tabel maka punya kolom dan baris. karena punya baris dan kolom maka numpy menyebutnya punya 2 axis (2 sumbu). axis 0 = arah ke bawah (baris), axis 1= arah ke samping (kolom).

# cara ambil data (indexing)
# dalam list of lists python, untuk indexing harus pakai dua kali square brackets '[]', a[1][3] (artinya: masuk ke baris indeks 1 dulu, baru masuk kolom indeks ke 3). sedangkan dalam numpy cukup tulis koordinat dalam satu kurung saja, a[1,3] (ambilkan data dari koordinat baris indeks 1 dan kolom indeks 3).
a[1,3]



np.int64(9)

Atribut Array (sifat-sifat dasar yang dimiliki setiap array di numpy)
====================================================================

In [14]:

# ndim, shape, size, and dtype 
# 1. ndim (number of dimentions): berapa jumlah dimensinya atau ada berapa axis?
#   Analogi:
#   --ndim = 1: Seperti garis lurus (hanya punya Panjang).
#   --ndim = 2: Seperti kertas/tabel (punya Panjang & Lebar).
#   --ndim = 3: Seperti kubus (punya Panjang, Lebar, & Tinggi).
#   Di Teks: a.ndim hasilnya 2. Artinya array a adalah sebuah tabel datar (2 Dimensi).

a.ndim


2

In [15]:
# 2. shape (bentuk, ukuran rinci): berapa panjang masing-masing sisi dimensinya?
#    Analogi: Jika ndim memberi tahu itu adalah "Tabel", maka shape memberi tahu "Tabel ukuran berapa?".
#    Di Teks: a.shape hasilnya (3, 5).
#   --Angka 3 = Ada 3 Baris.
#   --Angka 4 = Ada 4 Kolom.
#   Hubungan: Jumlah angka di dalam (3, 5) ada dua buah, ini membuktikan ndim-nya adalah 2.

a.shape

(3, 5)

In [16]:
# 3. size (Total Ukuran/Isi): Ada berapa total elemen (angka) di dalam seluruh array ini?
#   Rumus: Hasil perkalian dari shape.
#   Di Teks: a.size hasilnya 15.
#   Didapat dari: 3 baris dikali 5 kolom = 15 kotak data.
#   Analogi: Jika shape adalah ukuran gedung (3 lantai x 4 kamar), maka size adalah total jumlah kamar di gedung itu (12 kamar).

a.size

15

In [17]:
# 4. dtype (Data Type / Jenis Bahan): Data jenis apa yang disimpan di dalamnya?
#   Aturan Penting: NumPy array bersifat "Homogeneous", artinya seluruh isinya harus seragam. Tidak boleh campur aduk (misalnya angka dicampur huruf).
#   Di Teks: a.dtype hasilnya int64.
#   Artinya, semua 12 kotak tadi berisi Integer (bilangan bulat).
#   64 berarti memorinya 64-bit (standar komputer modern).

a.dtype

dtype('int64')

Bagaimana caranya membuat basic array
======================================

np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

1.np.zeros() membuat array yang berisi data 0

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

2. np.ones() membuat array yang berisi 1 

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

3. np.empty() 
Maksudnya "Empty" (Kosong) Itu Apa?
Di dunia komputer, "Empty" di sini bukan berarti "Hampa" atau "Nol". Artinya adalah: "Tolong pesankan tempat di memori, tapi jangan dibersihkan isinya." Ketika komputer memberikan tempat memori untuk array tersebut, komputer tidak menghapus jejak data yang pernah ada di sana sebelumnya. Jadi, angka yang muncul apapun itu adalah "Sampah Memori" (Garbage Value)—sisa-sisa data dari program lain yang kebetulan pernah memakai alamat memori tersebut.
Analogi: Kamar Hotel
Bayangkan Anda adalah resepsionis hotel.
np.zeros() (Array isi Nol): Tamu datang. Sebelum Anda kasih kunci, Anda suruh Cleaning Service bersihkan kamar sampai kinclong, sprei diganti baru, lantai disapu bersih (di-set jadi 0).
Hasil: Kamar bersih (nilainya 0 semua). Konsekuensi: Agak Lambat, karena butuh waktu untuk bersih-bersih.

np.empty() (Array Kosong): Tamu datang. Anda langsung lempar kuncinya. "Nih kamarnya, langsung masuk aja!". Anda tidak menyuruh Cleaning Service masuk dulu.
Hasil: Di dalam kamar mungkin masih ada sisa sampah tamu sebelumnya (bisa ada botol minum, kertas bekas, dll). Itulah angka acak 3.14 atau 42 tadi. Konsekuensi: Sangat Cepat, karena tidak perlu waktu bersih-bersih.

kenapa pakai empty? karena speed, juga biasa digunakan sebagai wadah sementara, sehingga ngapain memori dibersihkan jadi 0 kalau satu detik kemudian ditimpa juga.

In [20]:
np.empty(2)

array([4.94065646e-324, 6.45193065e-310])

4. np.arange() membuat array dengan range dari elemen

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
# bisa juga dengan menentukan angka awal, angka akhir, dan step size, np.arange(nilai awal, nilai akhir, step size)
np.arange(2,11,2)  # np buatkan array dengan range (angka awal 2, angka akhir 11, dengan 2 'langkah')

array([ 2,  4,  6,  8, 10])

5. np.linspace()
Ini adalah fungsi penyelamat ketika malas menghitung matematika. np.linspace adalah singkatan dari Linear Space (Spasi yang Linear/Rata). bedanya dengan metode biasa, menggunakan analogi Memasang Tiang Lampu.
Analogi: Proyek Tiang Lampu Jalan
Bayangkan Anda adalah kontraktor jalan raya sepanjang 10 meter (dari meter ke-0 sampai meter ke-10).

    1. Cara Lama (np.arange): Fokus pada Langkah Bos Anda bilang: "Pasang tiang dari meter 0 sampai 10, jarak antar tiang harus 2.5 meter." Anda harus menghitung manual: 0, lalu 2.5, lalu 5... dst. Anda mengatur Jaraknya. Anda tidak tahu nanti totalnya jadi berapa tiang, pokoknya pasang saja.

    2. Cara np.linspace: Fokus pada Jumlah (Target) Bos Anda bilang: "Saya tidak peduli jaraknya berapa, pokoknya dari meter 0 sampai 10, saya mau di situ tertancap tegak 5 tiang dengan jarak yang rata." Di sinilah np.linspace bekerja. Komputer yang akan pusing menghitung jaraknya, Anda tinggal terima beres.


In [23]:
np.linspace(0,10, num=5)


# Bedah Kode

# np.linspace(0, 10, num=5)

# 0 (Start): Mulai dari mana? (Titik Awal).
# 10 (Stop): Berhenti di mana? (Titik Akhir). Penting: Di linspace, angka 10 ini ikut masuk (inklusif).
# num=5 (Number): Mau dipotong jadi berapa bagian/titik?
# Hasilnya: array([ 0. , 2.5, 5. , 7.5, 10. ])

# Komputer secara otomatis membagi jarak 0 ke 10 agar muat persis untuk 5 angka. (0 -> 2.5 -> 5.0 -> 7.5 -> 10.0)
# Kapan Pakai Ini?
# Fungsi ini sangat sering dipakai saat Membuat Grafik (Plotting).
# Misalnya, Anda ingin menggambar kurva mulus. Anda butuh ribuan titik koordinat dari X=0 sampai X=100. Daripada bikin manual, cukup ketik: x = np.linspace(0, 100, num=1000) Maka Anda akan punya 1000 titik yang tersebar rapi untuk menggambar garis kurva yang halus.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
# manual override, secara default tipe data array dalam numpy adalah float64 (presisi tinggi, aman untuk perhitungan matematika, cirinya ada titik di belakang angak, 0., 1., ). kenapa dan kapan harus pakai dtype? untuk hemat ram, data gambar (biasanya format uint8(bilangan bulat 0-255), bukan desimal), index/id (no. antrian, no. id jarang pakai desimal bahkan tidak ada)

# dg menetapkan langsung tipe data
np.ones(4, dtype=np.int64)

array([1, 1, 1, 1])

In [25]:
# default 
np.ones(4)

array([1., 1., 1., 1.])

Adding, removing, dan sorting elemen

np.sort(), np.concatenate()

In [26]:
# np.sort()

arr = np.array ([2,4,6,7,8,1,3,5])
arr

array([2, 4, 6, 7, 8, 1, 3, 5])

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.argsort(arr)

array([5, 0, 6, 1, 7, 2, 3, 4])

In [29]:
np.lexsort(arr)

np.int64(0)

In [30]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])